use_frameworks!

target 'NicooDownload_Example' do
  pod 'NicooDownload', :path => '../'
  
  pod 'NicooTableListViewController'
  
  target 'NicooDownload_Tests' do
    inherit! :search_paths

    
  end
end
